### ISSUE TITLE
SD3?

### ISSUE THREAD

**Issue by clawnotfound** [yangxiaofeng/rectified_flow_prior#1]
Hello, thank very much for your great work! but i wonder when/how can i do model inversion for SD3 use your elegant method?

**Comment by yangxiaofeng** [comment]
Hi,

Working on it. We're probably rolling out support for sd3 this week. I've got the RFDS baseline working on sd3 now, and it's performing better than Instaflow. I'm still tuning iRFDS and RFDS-Rev, though.

**Comment by yangxiaofeng** [comment]
SD3 support added.
