### ISSUE TITLE
An error occurred when batch size was set to 2.

### ISSUE THREAD

**Issue by Rody1911641** [yangxiaofeng/rectified_flow_prior#5]
Thank you for your amazing paper and ingenious formula derivation. But an error occurred when batch size was set to 2:
data:
  batch_size: [2, 2]
I run this command: python launch.py --config configs/rfds_sd3.yaml --train system.prompt_processor.prompt="a zoomed out DSLR photo of a baby bunny sitting on top of a stack of pancakes".

The error log:
File "/rectified_flow_prior-main/threestudio/systems/rf.py", line 73, in training_step
    self.log(f"train/{name}", value)
ValueError: `self.log(train/loss_rfds, tensor([14.2471, 22.4035], device='cuda:0'))` was called, but the tensor must have a single element. You can try doing `self.log(train/loss_rfds, tensor([14.2471, 22.4035], device='cuda:0').mean())

**Comment by yangxiaofeng** [comment]
Hey, thanks for the bug report! I'll push a fix for the issue on RFDS SD3.
