### ISSUE TITLE
Questiones about "Rectified Flow Time Inversion"

### ISSUE THREAD

**Issue by bookkkker** [yangxiaofeng/rectified_flow_prior#7]
Hi!! Your work is so great!!But I don't know rectified flow theory very much,So can you tell me how can I achieve the "Rectified Flow Time Inversion"? Thank you !!

**Comment by yangxiaofeng** [comment]
Hi, thank you for your interest in our work! You may need to modify the original rectified flow pipeline (pipeline_rf.py). Change the previous noise-to-image flow to image-to-noise.

**Comment by bookkkker** [comment]
Thanks to your reply! My aim is to get the latent that can reconstruct the same image as the input,I tried to modify the pipeline to achieve image-to-noise,but I failed to reconstruct the input image by this noise latent, Can you tell me more about it?Or is there any reference code for me to study? Thank you again!
![屏幕截图 2024-09-29 210758](https://github.com/user-attachments/assets/dc451993-2d0f-4dce-a794-5c5a29db0982)
On your paper says  t → 1 − 0 and taking a negative velocity,maybe there are any other details I don't catch.

**Comment by yangxiaofeng** [comment]
Hi, I have uploaded my code of this part in the repo. Please have a look. Do note that based on our experiments the results of this method are not as good as other methods.
